controller:
  nodeSelector:
    kubernetes.io/os: linux
  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/os: linux

defaultBackend:
  nodeSelector:
    kubernetes.io/os: linux

