apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: asore@nuuday.dk
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testcert-aws-nuuday-nu
  namespace: default
spec:
  secretName: testcert-aws-nuuday-nu-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: testcert.aws.nuuday.nu
  dnsNames:
  - testcert.aws.nuuday.nu
