apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
  labels:
    app: cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      containers:
      - name: cm
        image: 273653477426.dkr.ecr.eu-central-1.amazonaws.com/odin-sitecore-xm1-cm:9.3.0-d8bd5939
        env:
        - name: SITECORE_FEDERATEDAUTHENTICATION_IDENTITY_SERVER_CALLBACKAUTHORITY
          value: "http://asore-cm.aws.nuuday.nu"
        - name: SITECORE_IDENTITY_SERVER_AUTHORITY
          value: "http://asore-sis.aws.nuuday.nu"
        - name: SITECORE_CONFIGURATION
          value: "LocalCM"
        - name: ENTRYPOINT_STDOUT_SITECORE_LOG_ENABLED
          value: "true"
        - name: ENTRYPOINT_STDOUT_IIS_ACCESS_LOG_ENABLED
          value: "true"
        - name: SITECORE_CONNECTIONSTRINGS_SOLR.SEARCH
          value: "http://solr.default.svc.cluster.local:8983/solr"
        - name: SITECORE_CONNECTIONSTRINGS_CORE
          valueFrom:
            configMapKeyRef:
              name: sitecore-connection-strings
              key: core
        - name: SITECORE_CONNECTIONSTRINGS_SECURITY
          valueFrom:
            configMapKeyRef:
              name: sitecore-connection-strings
              key: security
        - name: SITECORE_CONNECTIONSTRINGS_MASTER
          valueFrom:
            configMapKeyRef:
              name: sitecore-connection-strings
              key: master
        - name: SITECORE_CONNECTIONSTRINGS_WEB
          valueFrom:
            configMapKeyRef:
              name: sitecore-connection-strings
              key: web
        - name: SITECORE_CONNECTIONSTRINGS_EXPERIENCEFORMS
          valueFrom:
            configMapKeyRef:
              name: sitecore-connection-strings
              key: experienceforms
        - name: SITECORE_LICENSE
          valueFrom:
            configMapKeyRef:
              name: sitecore-license
              key: license
---
apiVersion: v1
kind: Service
metadata:
  name: cm
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.kubernetes.io/local-svc-only-bind-node-with-pod: "true"
spec:
  selector:
    app: cm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cm-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    service.kubernetes.io/local-svc-only-bind-node-with-pod: "true"
spec:
  rules:
  - host: asore-cm.aws.nuuday.nu
    http:
      paths:
      - path: /
        backend:
          serviceName: cm
          servicePort: 80
