apiVersion: v1
kind: ConfigMap
metadata:
  name: sitecore-connection-strings
data:
  core: Data Source=sqlserver.default.svc.cluster.local;Initial Catalog=Sitecore.Core;User ID=sa;Password=!2Secure2017#
  security: Data Source=sqlserver.default.svc.cluster.local;Initial Catalog=Sitecore.Core;User ID=sa;Password=!2Secure2017#
  web: Data Source=sqlserver.default.svc.cluster.local;Initial Catalog=Sitecore.Web;User ID=sa;Password=!2Secure2017#
  master: Data Source=sqlserver.default.svc.cluster.local;Initial Catalog=Sitecore.Master;User ID=sa;Password=!2Secure2017#
  experienceforms: Data Source=sqlserver.default.svc.cluster.local;Initial Catalog=Sitecore.ExperienceForms;User ID=sa;Password=!2Secure2017#
